[build-system]
requires        = ["setuptools>=61.0.0"]
build-backend   = "setuptools.build_meta"

[project]
name            = "gwmlt"
version         = "0.1.0"
description     = "Machine learning workflows for gravitational wave astronomy"
readme          = "README.md"
requires-python = ">=3.13, <3.14"

dependencies = [
    # Core
    "numpy",
    "scipy",
    "matplotlib",

    # Data handling
    "pandas",
    "h5py",
    "tables",

    # Astrophysics
    "pycbc",
    "lalsuite",
    "astropy",

    # Machine learning
    "torch",

    # Miscellaneous
    "juliacall",
    "tqdm",
    "notebook",
]

authors = [
    { name = "Sparsha Ray", email = "sparsharay@gmail.com" }
]

license = "GPL-3.0-only"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.13",
]

[tool.pixi.workspace]
channels  = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "3.13.*"
pytest = "*"
pip = "*"
gsl = "*"
gcc = "*"

[tool.pixi.pypi-dependencies]
gwmlt = { path = ".", editable = true }

[tool.pixi.tasks]
install-teobresums = "bash scripts/install_teobresums.sh"
install-chypergeom = "bash scripts/install_chypergeom.sh"
tests = "pytest -v" 