[build-system]
requires        = ["setuptools>=61.0.0"]
build-backend   = "setuptools.build_meta"

[project]
name            = "gwmlt"
version         = "0.1.0"
description     = "Machine learning workflows for gravitational wave astronomy"
readme          = "README.md"
requires-python = ">=3.13, <3.14"

dependencies = [
    # Core
    "numpy",
    "scipy >= 1.18",
    "juliacall",
    "matplotlib",
    "seaborn",

    # Data handling
    "sqlmodel",
    "pymysql",
    "pyarrow",
    "pandas",
    "tables",
    "h5py",

    # Astronomy and GW-related
    "astropy",
    "pycbc ~= 2.10.0",
    "gwpopulation",
    "lalsuite",
    "bilby",

    # Machine learning
    "torch",
    "torchvision",
    "scikit-learn",
    "scikit-image",
    "timm",

    # Cluster computing
    "dask[complete]",
    "dask-jobqueue",

    # Miscellaneous
    "tqdm",
    "notebook",
    "pyinstrument",
    "marimo[recommended]",
]

authors = [
    { name = "Sparsha Ray", email = "sparsharay@gmail.com" }
]

license = "GPL-3.0-only"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.13",
]

[tool.pixi.workspace]
channels  = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "3.13.*"
pytest = "*"
mysql = "*"
pip = "*"
gsl = "*"
gcc = "*"

[tool.pixi.pypi-dependencies]
gwmlt = { path = ".", editable = true }

[tool.setuptools.package-data]
"gwmlt" = ["data/**/*"]

[tool.pixi.tasks]
install-teobresums = "bash scripts/install_teobresums.sh"
install-chypergeom = "bash scripts/install_chypergeom.sh"
tests = "pytest -v" 